---
trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: git
      name: ${project_name}/${repository_name_templates}

parameters:
  - name: environment
    displayName: 'Choose Environment'
    type: string
    default: All
    values:
      - All
%{ for environment in environments ~}
      - ${environment.name}
%{ endfor ~}
  - name: terraform_action
    displayName: Terraform Action to perform
    type: string
    default: 'apply'
    values:
      - 'apply'
      - 'destroy'
  - name: terraform_cli_version
    displayName: Terraform CLI Version
    type: string
    default: 'latest'

lockBehavior: sequential

extends:
  template: ${cd_template_path}@templates
  parameters:
    terraform_action: $${{ parameters.terraform_action }}
    root_module_folder_relative_path: ${root_module_folder_relative_path}
    environment: $${{ parameters.environment }}
    terraform_cli_version: $${{ coalesce(parameters.terraform_cli_version, 'latest') }}
    environments: 
%{ for environment in environments ~}
      - name: ${environment.name}
        display_name: ${environment.display_name}
        service_connection_name_plan: ${environment.service_connection_name_plan}
        service_connection_name_apply: ${environment.service_connection_name_apply}
        variable_group_name: ${environment.variable_group_name}
        agent_pool_type: ${environment.agent_pool_type}
        agent_pool_name: ${environment.agent_pool_name}
        environment_name: ${environment.environment_name}
        dependent_environment: ${environment.dependent_environment}
%{ endfor ~}
